[window]
#decorations = "Buttonless"
decorations = "None"
dynamic_padding = false
startup_mode = "Windowed"
option_as_alt = "Both"

[window.dimensions]
columns = 120
lines = 100

[window.padding]
x = 5
y = 5
