title: Dotfiles
description: Personal dotfiles managed with rcm
baseurl: "/dotfiles"
url: "https://vairav.github.io"

remote_theme: just-the-docs/just-the-docs

color_scheme: dark

search_enabled: true
search:
  heading_level: 2
  previews: 3

nav_enabled: true
back_to_top: true
back_to_top_text: "Back to top"

aux_links:
  "GitHub":
    - "https://github.com/vairav/dotfiles"

aux_links_new_tab: true
